### ISSUE TITLE
CircleImageView Dependency

### ISSUE THREAD

**Issue by mikekpl** [Mindinventory/OverlapImageGalleryView#3]
Hi, This is more for improvement. 

Just saw that you were using CircleImageView as a dependency, thinking that Glide already has circleCrop feature and I think it can replace CircleImageView?

**Comment by akashmi** [comment]
Hi @mike14u 
Thanks for the suggestion. CircleImageView is part of the example, not the library. user can use anything as per his choice. 
and I will also implement it this example.

**Comment by akashmi** [comment]
Updated it in the example.

**Comment by mikekpl** [comment]
Cool thanks @akashmi
