### ISSUE TITLE
Images not showing when the list is less than the overlap limit

### ISSUE THREAD

**Issue by EngMahmoudMagdy** [Mindinventory/OverlapImageGalleryView#5]
Hi, Thanks so much for your efforts here.
I found that the list of images not showing when the data is less than the overlap limit
Example:
If the data is 4 images only and the overlap limit is 10 images then it will show the counter, the 4 images are not showing as expected. 
Could you please help me ?

**Comment by xyzvoyager** [comment]
@EngMahmoudMagdy Just check the latest release
